#!/bin/bash

log() {
	if [[ -t 1 ]]; then
		echo -e "\x1b[1m\x1b[32m>>>\x1b[0m \x1b[1m\x1b[37m$1\x1b[0m"
	else
		echo ">>> $1"
	fi
}

log "Running tests under $SHELL ..."

error=0
for test in $(dirname $0)/*_test.sh; do
	log "Running $test ..."
	$SHELL $test || error=1
	echo
done

exit $error
