#!/bin/bash

. ./test/helper.sh

function log() {
	if [[ -t 1 ]]; then
		echo -e "\x1b[1m\x1b[32m>>>\x1b[0m \x1b[1m\x1b[37m$1\x1b[0m"
	else
		echo ">>> $1"
	fi
}

function error() {
	if [[ -t 1 ]]; then
		echo -e "\x1b[1m\x1b[31m!!!\x1b[0m \x1b[1m\x1b[37m$1\x1b[0m" >&2
	else
		echo "!!! $1" >&2
	fi
}

function fail() {
	error "$1"
	exit -1
}

function download() {
	if command -v wget; then
		wget -c -O "$2" "$1"
	elif command -v curl; then
		curl -L -C - -o "$2" "$1"
	else
		error "Could not find wget or curl"
		return 1
	fi
}

function detect_system() {
  # adapted from RVM: https://github.com/wayneeseguin/rvm/blob/master/scripts/functions/utility_system#L3
  SYSTEM_TYPE="unknown"
  SYSTEM_NAME="unknown"
  SYSTEM_VERSION="unknown"
  SYSTEM_ARCH="$(uname -m)"

  case "$(uname)" in
    (Linux|GNU*)
      SYSTEM_TYPE="linux"

      if [[ -f /etc/lsb-release ]] &&
	 [[ "$(< /etc/lsb-release)" == *"DISTRIB_ID=Ubuntu"* ]]
      then
        SYSTEM_NAME="ubuntu"
        SYSTEM_VERSION="$(awk -F'=' '$1=="DISTRIB_RELEASE"{print $2}' /etc/lsb-release)"
        SYSTEM_ARCH="$(dpkg --print-architecture)"
      elif [[ -f /etc/lsb-release ]] &&
           [[ "$(< /etc/lsb-release)" == *"DISTRIB_ID=LinuxMint"* ]]
      then
        SYSTEM_NAME="mint"
        SYSTEM_VERSION="$(awk -F'=' '$1=="DISTRIB_RELEASE"{print $2}' /etc/lsb-release)"
        SYSTEM_ARCH="$( dpkg --print-architecture )"
      elif [[ -f /etc/lsb-release ]] &&
           [[ "$(< /etc/lsb-release)" == *"DISTRIB_ID=ManjaroLinux"* ]]
      then
        SYSTEM_NAME="manjaro"
        SYSTEM_VERSION="$(awk -F'=' '$1=="DISTRIB_RELEASE"{print $2}' /etc/lsb-release)"
      elif [[ -f /etc/os-release ]] &&
           [[ "$(< /etc/os-release)" == *"ID=opensuse"* ]]
      then
        SYSTEM_NAME="opensuse"
        SYSTEM_VERSION="$(awk -F'=' '$1=="VERSION_ID"{gsub(/"/,"");print $2}' /etc/os-release)" #'
      elif [[ -f /etc/SuSE-release ]]; then
        SYSTEM_NAME="suse"
        SYSTEM_VERSION="$(
          awk -F'=' '{gsub(/ /,"")} $1~/VERSION/ {version=$2} $1~/PATCHLEVEL/ {patch=$2} END {print version"."patch}' < /etc/SuSE-release
        )"
      elif [[ -f /etc/debian_version ]]; then
        SYSTEM_NAME="debian"
        SYSTEM_VERSION="$(< /etc/debian_version | awk -F. '{print $1"."$2}')"
        SYSTEM_ARCH="$( dpkg --print-architecture )"
      elif [[ -f /etc/os-release ]] &&
           [[ "$(< /etc/os-release)" == *"ID=debian"* ]]
      then
        SYSTEM_NAME="debian"
        SYSTEM_VERSION="$(awk -F'=' '$1=="VERSION_ID"{gsub(/"/,"");print $2}' /etc/os-release | awk -F. '{print $1"."$2}')" #'
        SYSTEM_ARCH="$( dpkg --print-architecture )"
      elif [[ -f /etc/fedora-release ]]; then
        SYSTEM_NAME="fedora"
        SYSTEM_VERSION="$(grep -Eo '[[:digit:]]+' /etc/fedora-release)"
      elif [[ -f /etc/centos-release ]]; then
        SYSTEM_NAME="centos"
        SYSTEM_VERSION="$(grep -Eo '[[:digit:]\.]+' /etc/centos-release | awk -F. '{print $1"."$2}')"
      elif [[ -f /etc/redhat-release ]]; then
        if [[ "$(< /etc/redhat-release)" == *"CentOS"* ]]; then
		SYSTEM_NAME="centos"
        else
		SYSTEM_NAME="redhat"
        fi

        SYSTEM_VERSION="$(grep -Eo '[[:digit:]\.]+' /etc/redhat-release | awk -F. '{print $1"."$2}')"
      elif [[ -f /etc/system-release ]] &&
           [[ "$(< /etc/system-release)" == *"Amazon Linux AMI"* ]]
      then
        SYSTEM_NAME="amazon"
        SYSTEM_VERSION="$(grep -Eo '[[:digit:]\.]+' /etc/system-release | awk -F. '{print $1"."$2}')"
      elif [[ -f /etc/gentoo-release ]]; then
        SYSTEM_NAME="gentoo"
        SYSTEM_VERSION="base-$(< /etc/gentoo-release | awk 'NR==1 {print $NF}' | awk -F. '{print $1"."$2}')"
      elif [[ -f /etc/arch-release ]]; then
        SYSTEM_NAME="arch"
        SYSTEM_VERSION="libc-$(ldd --version | awk 'NR==1 {print $NF}' | awk -F. '{print $1"."$2}')"
      else
        SYSTEM_VERSION="libc-$(ldd --version | awk 'NR==1 {print $NF}' | awk -F. '{print $1"."$2}')"
      fi
      ;;

    (SunOS)
      SYSTEM_TYPE="sunos"
      SYSTEM_NAME="solaris"
      SYSTEM_VERSION="$(uname -v)"

      if [[ "${SYSTEM_VERSION}" == joyent* ]]; then
        SYSTEM_NAME="smartos"
        SYSTEM_VERSION="${SYSTEM_VERSION#* }"
      elif [[ "${SYSTEM_VERSION}" == oi* ]]; then
        SYSTEM_NAME="openindiana"
        SYSTEM_VERSION="${SYSTEM_VERSION#* }"
      fi
      ;;

    (OpenBSD)
      SYSTEM_TYPE="bsd"
      SYSTEM_NAME="openbsd"
      SYSTEM_VERSION="$(uname -r)"
      ;;

    (Darwin)
      SYSTEM_TYPE="darwin"
      SYSTEM_NAME="osx"
      SYSTEM_VERSION="$(sw_vers -productVersion)"
      SYSTEM_VERSION="${SYSTEM_VERSION%.*}" # only major.minor - teeny is ignored
      ;;

    (FreeBSD)
      SYSTEM_TYPE="bsd"
      SYSTEM_NAME="freebsd"
      SYSTEM_VERSION="$(uname -r)"
      SYSTEM_VERSION="${SYSTEM_VERSION%%-*}"
      ;;

    (*)
      return 1
      ;;
  esac

  SYSTEM_TYPE="${SYSTEM_TYPE//[ \/]/_}"
  SYSTEM_NAME="${SYSTEM_NAME//[ \/]/_}"
  SYSTEM_VERSION="${SYSTEM_VERSION//[ \/]/_}"
  SYSTEM_ARCH="${SYSTEM_ARCH//[ \/]/_}"
  SYSTEM_ARCH="${SYSTEM_ARCH/amd64/x86_64}"
  SYSTEM_ARCH="${SYSTEM_ARCH/i[123456789]86/i386}"
}

detect_system || fail "Cannot auto-detect system type"
[[ "$SYSTEM_NAME" == "unknown"    ]] && fail "Could not detect system name"
[[ "$SYSTEM_VERSION" == "unknown" ]] && fail "Could not detect system version"
[[ "$SYSTEM_ARCH" == "unknown"    ]] && fail "Could not detect system arch"

TEST_RUBY_ARCHIVE="$TEST_RUBY_ENGINE-$TEST_RUBY_VERSION-p$TEST_RUBY_PATCHLEVEL.tar.bz2"
TEST_RUBY_URL="http://rvm.io/binaries/$SYSTEM_NAME/$SYSTEM_VERSION/$SYSTEM_ARCH/$TEST_RUBY_ARCHIVE"
TEST_RUBY_ROOT="$TEST_RUBY_ENGINE-$TEST_RUBY_VERSION-p$TEST_RUBY_PATCHLEVEL"

mkdir -p test/rubies
cd test/rubies

log "Downloading $TEST_RUBY_URL ..."
download "$TEST_RUBY_URL" "$TEST_RUBY_ARCHIVE" || fail "Download failed"

log "Unpacking $TEST_RUBY_ARCHIVE ..."
tar -xjf "$TEST_RUBY_ARCHIVE" || fail "Unpacking failed"
