.TH "CHRUBY" "1" "January 2013" "postmodern" "Ruby Programmers Reference Guide"
.BR chruby (1) 
\-\- Changes the current Ruby.
.SH SYNOPSIS
.PP
\fB\fCchruby\fR [RUBY|VERSION|system] [RUBY_OPTS]
.SH DESCRIPTION
.PP
Changes the current Ruby version by correctly setting the appropriate environment variables. Additional documentation available at https://github.com/postmodern/chruby/blob/master/README.md
.UR https://github.com/postmodern/chruby/blob/master/README.md
.UE .
.SH OPTIONS
.PP
\fB\fC-h\fR, \fB\fC--help\fR
.SH EXAMPLES
.PP
List available Rubies:
    $ chruby
     ruby\-1.9.3\-p327
     jruby\-1.7.0
     rubinius\-2.0.0\-rc1
.PP
Select a Ruby:
    $ chruby 1.9.3
    $ chruby
     * ruby\-1.9.3\-p327
       jruby\-1.7.0
       rubinius\-2.0.0\-rc1
.PP
Switch to JRuby in 1.9 mode:
    $ chruby jruby \-\-1.9
.PP
Switch back to system Ruby:
    $ chruby system
.PP
Switch to an arbitrary Ruby on the fly:
    $ chruby_use /path/to/ruby
.SH FILES
.PP
~/.gem/$ruby/$version
.PP
/path/to/$ruby/$gemdir
.SH ENVIRONMENT
.PP
PATH Updated to include Rubies and RubyGems bin/ directories.
.PP
GEM_HOME
.PP
GEM_PATH
.PP
RUBY_ROOT
.PP
RUBY_ENGINE
.PP
RUBY_VERSION
.PP
GEM_ROOT
.PP
RUBYOPT Optionally set if second arguement is given.
.SH AUTHORS
.PP
Designed and implemented by Postmodern postmodern\.mod3@gmail\.com
.ME .
.SH SEE ALSO
.PP
.BR ruby (1), 
.BR gem (1)